# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : pings the developer
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "🎫 Ping › Developer"
run-name: "🎫 Ping › Developer"

# ---------------------------------------------------------------------------------------
#   triggers
# ---------------------------------------------------------------------------------------

on:
  issue_comment:
    types: [created]

# ---------------------------------------------------------------------------------------
#   environment variables
# ---------------------------------------------------------------------------------------

env:
  LABEL_ACCEPT:         "Status 𐄂 Accepted"

  ASSIGN_USER:          Aetherinox
  BOT_NAME_1:           AdminServ
  BOT_NAME_2:           AdminServX
  BOT_NAME_3:           EuropaServ
  BOT_NAME_DEPENDABOT:  dependabot[bot]

# ---------------------------------------------------------------------------------------
#   jobs
#
#   env not available for job.if
# ---------------------------------------------------------------------------------------

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
        contains(github.event.comment.body, '/ping')
    steps:

        # ---------------------------------------------------------------------------------------
        #   Add Label to accepted PR
        # ---------------------------------------------------------------------------------------

        - name: Send mail
          uses: dawidd6/action-send-mail@v3
          with:
                # Specify connection via URL (replaces server_address, server_port, secure,
                # username and password)
                #
                # Format:
                #
                #  * smtp://user:password@server:port
                #  * smtp+starttls://user:password@server:port
                # Required mail server address if not connection_url:
                server_address: ${{secrets.EMAIL_SMTP}}
                # Server port, default 25:
                server_port: 25
                # Optional whether this connection use TLS (default is true if server_port is 465)
                secure: true
                # Optional (recommended) mail server username:
                username: ${{secrets.EMAIL_FROM}}
                # Optional (recommended) mail server password:
                password: ${{secrets.EMAIL_KEY}}
                # Required mail subject:
                subject: Github Actions job result
                # Required recipients' addresses:
                to: ${{secrets.EMAIL_TO}}
                # Required sender full name (address can be skipped):
                from: ${{secrets.EMAIL_FROM}}  # <user@example.com>
                # Optional plain body:
                body: Build job of ${{github.repository}} completed successfully!
                # Optional HTML body read from file:
                html_body: |
                  <html>
                    <body>
                        this is a text email
                    </body>
                  </html>
                # Optional unsigned/invalid certificates allowance:
                ignore_cert: true
                # Optional converting Markdown to HTML (set content_type to text/html too):
                convert_markdown: true
                # Optional priority: 'high', 'normal' (default) or 'low'
                priority: normal

        - name: "🏷️ Notify Developer › ${{ env.ASSIGN_USER }}"
          env:
                CONTACT: ${{ secrets.EMAIL_TO }}
          run: |
                echo "My message" | mail -s "Github Notification" ${{ secrets.EMAIL_TO }}
